services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    environment:
      RAM_SIZE: "32G"
      CPU_CORES: "8"
      USERNAME: "admin"
      PASSWORD: "q1qq1q"
    restart: always
    stop_grace_period: 2m
